### ISSUE TITLE
为什么 pybind11 和 boost 一起用？只用 pybind11 不行吗？

### ISSUE THREAD

**Issue by Gwill** [pzxbc/py-ctp-service#1]
为什么 pybind11 和 boost 一起用？只用 pybind11 不行吗？

**Comment by pzxbc** [comment]
之所以需要boost，是因为有两个依赖：variant和locale

locale这个是用于编码转换，因为ctp默认返回的是gbk编码，但是pybind11默认字符串是utf-8编码的

variant是为了便于将ctp的所有结构体都封装成一个结构

ctp中所有的结构体都可以映射成python的dict，如果ctp结构体中每个字段都是char[]类型，那就直接使用std::map<string, string>结构体就行，但是字段的类型有int，char，char[], double，所以就弄了个boost:variant封装了一下。 c++17自带了variant类型，但是现在大部分的编译器还是支持到c++14.

关于代码中将ctp结构体都映射成ctp_struct，然后对应成python的dict这一点，我的想法是避免写ctp_struct的文档，所有dict中的字段都可以查ctp的头文件来了解。同时也方便本身熟悉ctp c代码的人使用

如果不想带boost那么大的包，其实这两个依赖可以从boost中抽出来
